services:
  app:
    image: 'astronnn/tickfocus'
    restart: always
    container_name: 'app'
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tickfocus
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

  db:
    image: 'postgres'
    restart: always
    container_name: 'db'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tickfocus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
